# Generated by Django 4.2.2 on 2024-10-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('country', models.TextField(blank=True, max_length=200, null=True, verbose_name='страна')),
                ('city', models.TextField(blank=True, max_length=200, null=True, verbose_name='город')),
                ('street', models.TextField(blank=True, max_length=200, null=True, verbose_name='улица')),
                ('house_number', models.TextField(blank=True, max_length=100, null=True, verbose_name='номер дома')),
                ('supplier_type', models.CharField(choices=[('завод', 0), ('розничная сеть', 1), ('индивидуальный предприниматель', 2)], default=0, verbose_name='тип организации')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
    ]
