# Generated by Django 4.2.2 on 2024-10-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0002_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('0', 'завод'), ('1', 'розничная сеть'), ('2', 'индивидуальный предприниматель')], default='0', verbose_name='тип организации'),
        ),
    ]
