# Generated by Django 4.2.2 on 2024-10-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0004_alter_supplier_supplier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('country', models.TextField(max_length=200, verbose_name='страна')),
                ('city', models.TextField(max_length=200, verbose_name='город')),
                ('street', models.TextField(max_length=200, verbose_name='улица')),
                ('house_number', models.TextField(max_length=8, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.AlterField(
            model_name='supplier',
            name='house_number',
            field=models.TextField(blank=True, max_length=8, null=True, verbose_name='номер дома'),
        ),
    ]
