# Generated by Django 4.2.2 on 2024-10-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0005_contact_alter_supplier_house_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('supplier_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность перед поставщиком')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkapp.contact', verbose_name='контакты')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkapp.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'звено',
                'verbose_name_plural': 'звенья',
            },
        ),
    ]
