# Generated by Django 4.2.2 on 2024-10-10 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0006_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата, время создания связи'),
            preserve_default=False,
        ),
    ]
