# Generated by Django 4.2.2 on 2024-10-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0007_link_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('0', 'завод'), ('1', 'розничная сеть'), ('2', 'индивидуальный предприниматель')], default='0', max_length=1, verbose_name='тип организации'),
        ),
        migrations.AlterField(
            model_name='link',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networkapp.link', verbose_name='поставщик'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
