# Generated by Django 4.2.2 on 2024-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0008_link_link_type_alter_link_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='products',
            field=models.ManyToManyField(to='networkapp.product', verbose_name='продукты'),
        ),
    ]
