# Generated by Django 4.2.2 on 2024-10-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0009_link_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='networkapp.link', verbose_name='поставщик'),
        ),
    ]
