# Generated by Django 4.2.2 on 2024-10-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0010_alter_link_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link_type',
        ),
        migrations.AddField(
            model_name='contact',
            name='link_type',
            field=models.CharField(choices=[('0', 'завод'), ('1', 'розничная сеть'), ('2', 'индивидуальный предприниматель')], default='0', max_length=1, verbose_name='тип организации'),
        ),
        migrations.AlterField(
            model_name='link',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='networkapp.contact', verbose_name='контакты'),
        ),
    ]
