# Generated by Django 4.2.2 on 2024-10-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0011_remove_link_link_type_contact_link_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'связь', 'verbose_name_plural': 'связи'},
        ),
    ]
